attempt artifact upload

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,6 +1,8 @@
 name: Android Builds
 
 on:
+  schedule:
+    - cron: "0 9 * * *"  # 9am UTC = 1am PST / 2am PDT. for all testapps except firestore
   pull_request:
     types: [opened, reopened, synchronize]
   workflow_dispatch:
@@ -153,7 +155,6 @@ jobs:
         shell: bash
         run: |
           set -x
-          
           python scripts/build_scripts/build_testapps.py --p Android \
             --t ${{ needs.check_and_prepare.outputs.apis }}  \
             --output_directory "${{ github.workspace }}" \
@@ -166,3 +167,43 @@ jobs:
       - name: Stats for ccache (mac and linux)
         if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
         run: ccache -s
+
+      - name: Prepare results summary artifact
+        if: ${{ !cancelled() }}
+        shell: bash
+        run: |
+          if [ ! -f build-results-android-${{ matrix.os }}.log.json ]; then
+            echo "__SUMMARY_MISSING__" > build-results-android-${{ matrix.os }}.log.json
+          fi
+
+      - name: Upload Android integration tests artifact
+        uses: actions/upload-artifact@v3
+        if: ${{ !cancelled() }}
+        with:
+          name: testapps-android-${{ matrix.os }}
+          path: testapps-android-${{ matrix.os }}
+          retention-days: ${{ env.artifactRetentionDays }}
+
+      - name: Upload Android build results artifact
+        uses: actions/upload-artifact@v3
+        if: ${{ !cancelled() }}
+        with:
+          name: log-artifact
+          path: build-results-android-${{ matrix.os }}*
+          retention-days: ${{ env.artifactRetentionDays }}
+
+      - name: Download log artifacts
+        if: ${{ needs.check_and_prepare.outputs.pr_number && failure() && !cancelled() }}
+        uses: actions/download-artifact@v3
+        with:
+          path: test_results
+          name: log-artifact
+
+      - name: Summarize build results
+        if: ${{ !cancelled() }}
+        shell: bash
+        run: |
+          cat build-results-android-${{ matrix.os }}.log
+          if [[ "${{ job.status }}" != "success" ]]; then
+            exit 1
+          fi
